// <auto-generated />
namespace ChatApplication.Data.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RoomRecordDateCreated : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RoomRecordDateCreated));
        
        string IMigrationMetadata.Id
        {
            get { return "201703250138345_RoomRecordDateCreated"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
